"""
app.py
------
Streamlit web app for the Student Performance Prediction project.

This is the Step 3 replacement for the console input() calls from
Step 1/2: instead of typing values into a terminal, the user fills out
a simple web form, and the already-trained model (from train_model.py)
predicts their final exam score.

Run with:
    streamlit run app.py

IMPORTANT: You must run `python train_model.py` first (Step 2), so that
model/linear_regression_model.pkl exists on disk for this app to load.
"""

import os
import joblib
import pandas as pd
import streamlit as st

MODEL_PATH = "model/linear_regression_model.pkl"

# -----------------------------------------------------------
# Page setup
# -----------------------------------------------------------
st.set_page_config(page_title="Student Performance Predictor", page_icon="🎓")
st.title("🎓 Student Performance Predictor")
st.write(
    "Enter a student's details below to predict their final exam score, "
    "using a Linear Regression model."
)

# -----------------------------------------------------------
# Load the trained model
# -----------------------------------------------------------
# We load it once here at the top of the script. Streamlit re-runs this
# whole file on every user interaction (e.g. clicking the button), but
# loading a small .pkl file is fast, so this is fine for now.
if not os.path.exists(MODEL_PATH):
    st.error(
        f"Model file not found at '{MODEL_PATH}'. "
        "Please run `python train_model.py` first to generate the data "
        "and train the model, then restart this app."
    )
    st.stop()

model = joblib.load(MODEL_PATH)

# -----------------------------------------------------------
# Input form (replaces the Step 1 console input() calls)
# -----------------------------------------------------------
st.subheader("Student Details")

study_hours = st.number_input(
    "Study hours per day", min_value=0.0, max_value=12.0, value=4.0, step=0.5
)
attendance = st.number_input(
    "Attendance percentage", min_value=0.0, max_value=100.0, value=80.0, step=1.0
)
previous_score = st.number_input(
    "Previous exam score", min_value=0.0, max_value=100.0, value=65.0, step=1.0
)
sleep_hours = st.number_input(
    "Sleep hours per night", min_value=0.0, max_value=12.0, value=6.5, step=0.5
)

# -----------------------------------------------------------
# Predict on button click
# -----------------------------------------------------------
if st.button("Predict Final Score"):
    new_student = pd.DataFrame([{
        "study_hours": study_hours,
        "attendance": attendance,
        "previous_score": previous_score,
        "sleep_hours": sleep_hours,
    }])

    predicted_score = model.predict(new_student)[0]

    # Same extrapolation issue you saw in Step 1 (a model can predict
    # above 100 or below 0 for unusual inputs) -- we clip it here just
    # for display, since a real exam score can't go outside that range.
    predicted_score_clipped = max(0, min(100, predicted_score))

    st.success(f"Predicted Final Exam Score: **{predicted_score_clipped:.2f}**")

    if predicted_score != predicted_score_clipped:
        st.caption(
            f"(Raw model output was {predicted_score:.2f}; clipped to the 0-100 range "
            "for display, since these inputs are outside the range the model was trained on.)"
        )

# -----------------------------------------------------------
# Optional: show the Actual vs Predicted plot from training,
# if it was generated by train_model.py
# -----------------------------------------------------------
plot_path = "model/actual_vs_predicted.png"
if os.path.exists(plot_path):
    st.subheader("Model Performance (on test data)")
    st.image(plot_path, caption="Actual vs Predicted scores from model evaluation")
